Repository ros2/rosidl_python, pull requests merged in 2019-03, with the labels that each got.

#32 Backport Python Actions
  python_cmake_module/cmake/Modules/FindPythonExtra.cmake
  rosidl_generator_py/cmake/custom_command.cmake
  rosidl_generator_py/cmake/register_py.cmake
  rosidl_generator_py/cmake/rosidl_generator_py_generate_action_interfaces.cmake
  rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake
  rosidl_generator_py/resource/_action.py.em
  rosidl_generator_py/resource/_msg_pkg_typesupport_entry_point.c.em
  rosidl_generator_py/resource/_srv.py.em
  rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
  rosidl_generator_py/rosidl_generator_py/import_type_support_impl.py
  rosidl_generator_py/test/test_interfaces.py
Labels: in progress

#24 change generators to IDL-based pipeline
  rosidl_generator_py/cmake/custom_command.cmake
  rosidl_generator_py/cmake/register_py.cmake
  rosidl_generator_py/cmake/rosidl_generator_py_generate_action_interfaces.cmake
  rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake
  rosidl_generator_py/resource/_action.py.em
  rosidl_generator_py/resource/_action_pkg_typesupport_entry_point.c.em
  rosidl_generator_py/resource/_idl.py.em
  rosidl_generator_py/resource/_idl_pkg_typesupport_entry_point.c.em
  rosidl_generator_py/resource/_idl_support.c.em
  rosidl_generator_py/resource/_msg.py.em
  rosidl_generator_py/resource/_msg_pkg_typesupport_entry_point.c.em
  rosidl_generator_py/resource/_msg_support.c.em
  rosidl_generator_py/resource/_srv.py.em
  rosidl_generator_py/resource/_srv_pkg_typesupport_entry_point.c.em
  rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
  rosidl_generator_py/test/test_interfaces.py
Labels: in review

#35 map Arrays to numpy.ndarray() and Sequences to array.array()
  rosidl_generator_py/CMakeLists.txt
  rosidl_generator_py/cmake/register_py.cmake
  rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake
  rosidl_generator_py/resource/_action.py.em
  rosidl_generator_py/resource/_idl.py.em
  rosidl_generator_py/resource/_msg.py.em
  rosidl_generator_py/resource/_msg_support.c.em
  rosidl_generator_py/resource/_srv.py.em
  rosidl_generator_py/rosidl_generator_py-extras.cmake.in
  rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
  rosidl_generator_py/test/test_interfaces.py
Labels: enhancement, in review

#34 Add rosidl_runtime_py package
  rosidl_runtime_py/package.xml
  rosidl_runtime_py/rosidl_runtime_py/__init__.py
  rosidl_runtime_py/rosidl_runtime_py/convert.py
  rosidl_runtime_py/rosidl_runtime_py/set_message.py
  rosidl_runtime_py/setup.py
  rosidl_runtime_py/test/rosidl_runtime_py/test_convert.py
  rosidl_runtime_py/test/rosidl_runtime_py/test_set_message.py
  rosidl_runtime_py/test/test_copyright.py
  rosidl_runtime_py/test/test_flake8.py
  rosidl_runtime_py/test/test_pep257.py
Labels: in review
