Repository ros2/rosidl_python, pull requests merged in 2019-05, with the labels that each got.

#49 [rosidl_runtime_py] Use new test interface definitions
  rosidl_runtime_py/test/rosidl_runtime_py/test_convert.py
Labels: in review

#51 Update tests that were missed during switch to use new interfaces
  rosidl_runtime_py/test/rosidl_runtime_py/test_set_message.py
Labels: in review

#47 add WString support
  rosidl_generator_py/CMakeLists.txt
  rosidl_generator_py/msg/WStrings.msg
  rosidl_generator_py/resource/_msg.py.em
  rosidl_generator_py/resource/_msg_support.c.em
  rosidl_generator_py/rosidl_generator_py/generate_py_impl.py
  rosidl_generator_py/test/test_interfaces.py
Labels: enhancement, in review

#53 add xmllint linter test
  rosidl_runtime_py/package.xml
  rosidl_runtime_py/test/test_xmllint.py
Labels: in review

#50 allow unicode chars in yaml output
  rosidl_runtime_py/rosidl_runtime_py/convert.py
Labels: in review

#55 fix conversion from C to Python in case a sequence has default values
  rosidl_generator_py/resource/_msg_support.c.em
Labels: bug, in review

#56 add missing numpy test dependency
  rosidl_generator_py/package.xml
Labels: bug, in review

#57 encode/decode strings with UTF-8
  rosidl_generator_py/resource/_msg_support.c.em
Labels: enhancement, in review

#58 fix PYTHONPATH for test
  rosidl_generator_py/CMakeLists.txt
Labels: bug, in review

#59 Fix the setting of array variables.
  rosidl_runtime_py/rosidl_runtime_py/set_message.py
Labels: in review

#62 fix logic around populating arrays
  rosidl_runtime_py/rosidl_runtime_py/set_message.py
Labels: bug, in review

#60 Make the message __repr__ for python look nicer.
  rosidl_generator_py/resource/_msg.py.em
Labels: in review
