Repository ros2/rosidl_python, pull requests merged in 2019-07, with the labels that each got.

#38 Add no_arr and no_str parameters
  rosidl_runtime_py/rosidl_runtime_py/convert.py
Labels: in review

#73 remove the padding member from structs which should be empty
  rosidl_generator_py/resource/_msg.py.em
  rosidl_generator_py/resource/_msg_support.c.em
Labels: enhancement, in review

#76 Remove non-package from ament_target_dependencies()
  rosidl_generator_py/CMakeLists.txt
  rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake
Labels: bug

#74 Make import_message_from_namespaced_type operate on NamespacedType
  rosidl_runtime_py/rosidl_runtime_py/import_message.py
  rosidl_runtime_py/rosidl_runtime_py/set_message.py
  rosidl_runtime_py/test/rosidl_runtime_py/test_import_message.py
Labels: bug
